# Generated by Django 5.2.4 on 2025-07-21 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='影城名稱')),
                ('location', models.CharField(max_length=200, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='片名')),
                ('description', models.TextField(blank=True, verbose_name='簡介')),
                ('duration', models.PositiveIntegerField(verbose_name='片長(分鐘)')),
                ('release_date', models.DateField(verbose_name='上映日')),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='廳名')),
                ('capacity', models.PositiveIntegerField(verbose_name='座位數')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_time', models.DateTimeField(verbose_name='放映時間')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.movie')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.screen')),
            ],
            options={
                'unique_together': {('screen', 'screening_time')},
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10, verbose_name='座位號')),
                ('is_reserved', models.BooleanField(default=False, verbose_name='是否已預訂')),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.screening')),
            ],
            options={
                'unique_together': {('screening', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.screening')),
                ('seats', models.ManyToManyField(to='tickets.seat')),
            ],
        ),
    ]
