# Generated by Django 5.0.14 on 2025-07-28 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_movie_image_movie_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='is_reserved',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='screening',
        ),
        migrations.AddField(
            model_name='seat',
            name='screen',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='tickets.screen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
